### ISSUE TITLE
Using pipes in shell command seems to have escaping problems

### ISSUE THREAD

**Issue by Viss** [MythicAgents/Medusa#2]
When attempting the following shell command:

```ps auxwww  | grep something ```

an error is returned saying that the pipe is an invalid character. 
Is there another way to run a piped shell command via medusa?

**Comment by ajpc500** [comment]
hey! very late to this, apologies - just updated this command (https://github.com/MythicAgents/Medusa/commit/4a972c59a8dc7305b10179b3e23292aa2c0cb75b), that should sort the piping issue. lmk if not!
