### ISSUE TITLE
error handling: name of ssl protocol does not exist on target system

### ISSUE THREAD

**Issue by gmatuz** [MythicAgents/Medusa#3]
Hi, 
somehow on one of the target systems the ssl module does not have  PROTOCOL_TLS as it is included here
https://github.com/MythicAgents/Medusa/blob/4309cbe97dc1d876bd0017aa03112ab102c37eff/Payload_Type/medusa/mythic/agent_functions/builder.py#L118

This results at the end in the following error:
`AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS'`

I'm not entirely sure how this happens, just fixed it up with the following, which ends up taking `PROTOCOL_TLSv1` on the system:
```
gcontext = ssl.SSLContext([e for e in dir(ssl) if e.startswith('PROTOCOL_TLS')][0])
if "PROTOCOL_TLS" in dir(ssl):
  gcontext = ssl.SSLContext(ssl.PROTOCOL_TLS)
```

I'm not sure how common this is, if it is worth adding

**Comment by ajpc500** [comment]
Hey, appreciate you flagging this, thank you! Had a play and have hopefully found a more sustainable alternative (https://github.com/MythicAgents/Medusa/commit/920f33d116bdc2cdbf7f93183dd0d4e23c9d69e7). Apologies i'm so late to this, but lmk how you get on!
