### ISSUE TITLE
Upload command

### ISSUE THREAD

**Issue by Chomikmarkus** [MythicAgents/Medusa#8]
Upload command seems not working! It adds in padding slashes and getting upload command output: 
[Errno 13] Permission denied: 'C:\\Users\\minka\\Downloads
Running it as Administrator

**Comment by Chomikmarkus** [comment]
When i compile medusa with pyinstaller shell failes with Winerror 6 handle error

**Comment by ajpc500** [comment]
hey @Chomikmarkus, for the upload command issue - are you first running `upload` and selecting the file in the pop up box? or trying to type it into the command line like `upload C:\Users\minka\Downloads`? i've just tested with a pyinstaller payload and upload seems fine used with the popup.

as for the shell command, could you pull my latest changes to `master` and see how that goes now? just tried that and it also seems ok with a pyinstaller payload on windows

**Comment by Chomikmarkus** [comment]
All working now! Was issue with target machine!

**Comment by Chomikmarkus** [comment]
upload works  but shell command after pyinstaller not still getting [winerror 6]The handle is invalid! Which version in medusa you tried with pyinstaller python3 or python2
![Screenshot_20211221-100404](https://user-images.githubusercontent.com/92059377/146893842-3808c4ad-d392-4992-bd95-55f74cf51ecd.png)

**Comment by Chomikmarkus** [comment]
![Uploading Screenshot_20211221-101105.png…]()

**Comment by Chomikmarkus** [comment]
![Screenshot_20211221-101105](https://user-images.githubusercontent.com/92059377/146894545-ab7247aa-6fe7-47c4-8500-8acec731c223.png)

**Comment by ajpc500** [comment]
this was Python3.10 and PyInstaller 4.7, running on Win10

**Comment by Chomikmarkus** [comment]
So tried it to reproduce!
![Screenshot_20211221-160803](https://user-images.githubusercontent.com/92059377/146943823-b8a09b35-e945-4d5a-bc54-9646ad3cbcd5.png)
![Screenshot_20211221-161056](https://user-images.githubusercontent.com/92059377/146943827-979b725b-13e2-4936-bb5d-8e2f13b10b74.png)

**Comment by Chomikmarkus** [comment]
command i use to for compile :PyInstaller --onefile --noconsole medusa.py! Python throws me  no errors!

**Comment by Chomikmarkus** [comment]
Hello! I solved this issue, all working now! 
Closing it! 
Thanks!
